version: "3"
services:
  sparkmaster:
    #image: gettyimages/spark:2.2.1-hadoop-2.7
    #image: gettyimages/spark:2.1.1-hadoop-2.7
    #image gettyimages/2.4.0-hadoop-3.0
    image: gettyimages/spark:latest
    #image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.master.Master -h sparkmaster
    hostname: sparkmaster
    container_name: sparkmaster
    environment:
      MASTER: spark://sparkmaster:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data
      - ..:/code
  sparkworker:
    #image: gettyimages/spark:2.2.1-hadoop-2.7
    image: gettyimages/spark:2.1.1-hadoop-2.7
    #image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://sparkmaster:7077
    hostname: sparkworker
    container_name: sparkworker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - sparkmaster
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
  gpdb:
      image: "kochanpivotal/gpdb5oss"
      hostname: "gpdbsne"
      container_name: gpdbsne
      command: bin/bash
      environment:
        - START_GPDB=yes
      ports:
       - "9090:9090"
       - "5432:5432"
       - "5005:5005"
       - "5010:5010"
       - "9022:22"
       - "40000:40000"
       - "40001:40001"
       - "40002:40002"
      expose:
       - "5432"
      volumes:
       - ..:/code
      links:
       - sparkmaster
      tty: true
